//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLForms.BL_ServiceReference {
    /// <summary>
    /// 
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Room", Namespace = "http://schemas.datacontract.org/2004/07/BE")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        /// <summary>
        /// 
        /// </summary>
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint BedsField;

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint PriceField;

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint RoomIDField;

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SeaWatchingField;

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomType TypeField;

        /// <summary>
        /// 
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Beds {
            get {
                return this.BedsField;
            }
            set {
                if ((this.BedsField.Equals(value) != true)) {
                    this.BedsField = value;
                    this.RaisePropertyChanged("Beds");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SeaWatching {
            get {
                return this.SeaWatchingField;
            }
            set {
                if ((this.SeaWatchingField.Equals(value) != true)) {
                    this.SeaWatchingField = value;
                    this.RaisePropertyChanged("SeaWatching");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// 
        /// </summary>
        /// <param name="propertyName"></param>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RoomType", Namespace = "http://schemas.datacontract.org/2004/07/BE")]
    public enum RoomType : int {
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regular = 0,
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suite = 1,
    }

    /// <summary>
    /// 
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Tour_Agency", Namespace = "http://schemas.datacontract.org/2004/07/BE")]
    [System.SerializableAttribute()]
    public partial class Tour_Agency : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        /// <summary>
        /// 
        /// </summary>
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint AgencyIDField;
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AgencyType TypeField;
        /// <summary>
        /// 
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint AgencyID {
            get {
                return this.AgencyIDField;
            }
            set {
                if ((this.AgencyIDField.Equals(value) != true)) {
                    this.AgencyIDField = value;
                    this.RaisePropertyChanged("AgencyID");
                }
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgencyType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// 
        /// </summary>
        /// <param name="propertyName"></param>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AgencyType", Namespace = "http://schemas.datacontract.org/2004/07/BE")]
    public enum AgencyType : int {

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        national = 0,

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        international = 1,

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        in_hotel_chain_ownership = 2,
    }

    /// <summary>
    /// 
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Reservation", Namespace = "http://schemas.datacontract.org/2004/07/BE")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Group_Reservation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Single_Reservation))]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint AgencyIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArrivalDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint BedsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint DaysField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LeavingDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint PriceField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ReservationIDField;

        /// <summary>
        /// 
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint AgencyID {
            get {
                return this.AgencyIDField;
            }
            set {
                if ((this.AgencyIDField.Equals(value) != true)) {
                    this.AgencyIDField = value;
                    this.RaisePropertyChanged("AgencyID");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((this.ArrivalDateField.Equals(value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Beds {
            get {
                return this.BedsField;
            }
            set {
                if ((this.BedsField.Equals(value) != true)) {
                    this.BedsField = value;
                    this.RaisePropertyChanged("Beds");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Days {
            get {
                return this.DaysField;
            }
            set {
                if ((this.DaysField.Equals(value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LeavingDate {
            get {
                return this.LeavingDateField;
            }
            set {
                if ((this.LeavingDateField.Equals(value) != true)) {
                    this.LeavingDateField = value;
                    this.RaisePropertyChanged("LeavingDate");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationDate {
            get {
                return this.ReservationDateField;
            }
            set {
                if ((this.ReservationDateField.Equals(value) != true)) {
                    this.ReservationDateField = value;
                    this.RaisePropertyChanged("ReservationDate");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ReservationID {
            get {
                return this.ReservationIDField;
            }
            set {
                if ((this.ReservationIDField.Equals(value) != true)) {
                    this.ReservationIDField = value;
                    this.RaisePropertyChanged("ReservationID");
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="propertyName"></param>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Group_Reservation", Namespace = "http://schemas.datacontract.org/2004/07/BE")]
    [System.SerializableAttribute()]
    public partial class Group_Reservation : Reservation {
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Room> RoomsField;

        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Room> Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Single_Reservation", Namespace = "http://schemas.datacontract.org/2004/07/BE")]
    [System.SerializableAttribute()]
    public partial class Single_Reservation : Reservation {
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Room RoomField;
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "BL_ServiceReference.IBL_SOAP")]
    public interface IBL_SOAP {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="room"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/AddRoom", ReplyAction = "http://tempuri.org/IBL_SOAP/AddRoomResponse")]
        bool AddRoom(Room room);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="Beds"></param>
        /// <param name="Type"></param>
        /// <param name="Price"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/UpdateRoom", ReplyAction = "http://tempuri.org/IBL_SOAP/UpdateRoomResponse")]
        bool UpdateRoom(uint ID, uint Beds, System.Nullable<RoomType> Type, uint Price);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/RemoveRoom", ReplyAction = "http://tempuri.org/IBL_SOAP/RemoveRoomResponse")]
        bool RemoveRoom(uint ID);
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/Rooms", ReplyAction = "http://tempuri.org/IBL_SOAP/RoomsResponse")]
        System.Collections.Generic.List<Room> Rooms();
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/NextRoomNumber", ReplyAction = "http://tempuri.org/IBL_SOAP/NextRoomNumberResponse")]
        uint NextRoomNumber();
        /// <summary>
        /// 
        /// </summary>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/reservedRooms", ReplyAction = "http://tempuri.org/IBL_SOAP/reservedRoomsResponse")]
        System.Collections.Generic.List<uint> reservedRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <param name="predicate"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/availableRooms", ReplyAction = "http://tempuri.org/IBL_SOAP/availableRoomsResponse")]
        System.Collections.Generic.List<Room> availableRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, System.Predicate<Room> predicate);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/roomIsAvailable", ReplyAction = "http://tempuri.org/IBL_SOAP/roomIsAvailableResponse")]
        bool roomIsAvailable(uint ID, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="agency"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/AddAgency", ReplyAction = "http://tempuri.org/IBL_SOAP/AddAgencyResponse")]
        bool AddAgency(Tour_Agency agency);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="Name"></param>
        /// <param name="ContactPerson"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/UpdateAgency", ReplyAction = "http://tempuri.org/IBL_SOAP/UpdateAgencyResponse")]
        bool UpdateAgency(uint ID, string Name, string ContactPerson);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/RemoveAgency", ReplyAction = "http://tempuri.org/IBL_SOAP/RemoveAgencyResponse")]
        bool RemoveAgency(uint ID);
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/Agencies", ReplyAction = "http://tempuri.org/IBL_SOAP/AgenciesResponse")]
        System.Collections.Generic.List<Tour_Agency> Agencies();
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/NextAgencyNumber", ReplyAction = "http://tempuri.org/IBL_SOAP/NextAgencyNumberResponse")]
        uint NextAgencyNumber();
        /// <summary>
        /// 
        /// </summary>
        /// <param name="reservation"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/AddReservation", ReplyAction = "http://tempuri.org/IBL_SOAP/AddReservationResponse")]
        bool AddReservation(Reservation reservation);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ReservationID"></param>
        /// <param name="ArrivalDate"></param>
        /// <param name="Days"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/UpdateReservation", ReplyAction = "http://tempuri.org/IBL_SOAP/UpdateReservationResponse")]
        bool UpdateReservation(uint ReservationID, System.Nullable<System.DateTime> ArrivalDate, uint Days);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ReservationID"></param>
        /// <param name="room"></param>
        /// <param name="ArrivalDate"></param>
        /// <param name="Days"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/UpdateSingleReservation", ReplyAction = "http://tempuri.org/IBL_SOAP/UpdateSingleReservationResponse")]
        bool UpdateSingleReservation(uint ReservationID, Room room, System.Nullable<System.DateTime> ArrivalDate, uint Days);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ReservationID"></param>
        /// <param name="rooms"></param>
        /// <param name="ArrivalDate"></param>
        /// <param name="Days"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/UpdateGroupReservation", ReplyAction = "http://tempuri.org/IBL_SOAP/UpdateGroupReservationResponse")]
        bool UpdateGroupReservation(uint ReservationID, System.Collections.Generic.List<Room> rooms, System.Nullable<System.DateTime> ArrivalDate, uint Days);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/RemoveReservation", ReplyAction = "http://tempuri.org/IBL_SOAP/RemoveReservationResponse")]
        bool RemoveReservation(uint ID);
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/Reservations", ReplyAction = "http://tempuri.org/IBL_SOAP/ReservationsResponse")]
        System.Collections.Generic.List<Reservation> Reservations();
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/NextReservationNumber", ReplyAction = "http://tempuri.org/IBL_SOAP/NextReservationNumberResponse")]
        uint NextReservationNumber();
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/ReservationsPrice", ReplyAction = "http://tempuri.org/IBL_SOAP/ReservationsPriceResponse")]
        uint ReservationsPrice();
        /// <summary>
        /// 
        /// </summary>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <returns></returns>
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBL_SOAP/cancelReservations", ReplyAction = "http://tempuri.org/IBL_SOAP/cancelReservationsResponse")]
        uint cancelReservations(System.DateTime start, System.DateTime end);
    }

    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBL_SOAPChannel : IBL_SOAP, System.ServiceModel.IClientChannel {
    }

    /// <summary>
    /// 
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BL_SOAPClient : System.ServiceModel.ClientBase<IBL_SOAP>, IBL_SOAP {
        /// <summary>
        /// 
        /// </summary>
        public BL_SOAPClient() {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="endpointConfigurationName"></param>
        public BL_SOAPClient(string endpointConfigurationName) :
            base(endpointConfigurationName) {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="endpointConfigurationName"></param>
        /// <param name="remoteAddress"></param>
        public BL_SOAPClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress) {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="endpointConfigurationName"></param>
        /// <param name="remoteAddress"></param>
        public BL_SOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress) {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="binding"></param>
        /// <param name="remoteAddress"></param>
        public BL_SOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress) {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="room"></param>
        /// <returns></returns>
        public bool AddRoom(Room room) {
            return base.Channel.AddRoom(room);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="Beds"></param>
        /// <param name="Type"></param>
        /// <param name="Price"></param>
        /// <returns></returns>
        public bool UpdateRoom(uint ID, uint Beds, System.Nullable<RoomType> Type, uint Price) {
            return base.Channel.UpdateRoom(ID, Beds, Type, Price);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public bool RemoveRoom(uint ID) {
            return base.Channel.RemoveRoom(ID);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public System.Collections.Generic.List<Room> Rooms() {
            return base.Channel.Rooms();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public uint NextRoomNumber() {
            return base.Channel.NextRoomNumber();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <returns></returns>
        public System.Collections.Generic.List<uint> reservedRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.reservedRooms(start, end);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <param name="predicate"></param>
        /// <returns></returns>
        public System.Collections.Generic.List<Room> availableRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, System.Predicate<Room> predicate) {
            return base.Channel.availableRooms(start, end, predicate);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <returns></returns>
        public bool roomIsAvailable(uint ID, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.roomIsAvailable(ID, start, end);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="agency"></param>
        /// <returns></returns>
        public bool AddAgency(Tour_Agency agency) {
            return base.Channel.AddAgency(agency);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="Name"></param>
        /// <param name="ContactPerson"></param>
        /// <returns></returns>
        public bool UpdateAgency(uint ID, string Name, string ContactPerson) {
            return base.Channel.UpdateAgency(ID, Name, ContactPerson);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public bool RemoveAgency(uint ID) {
            return base.Channel.RemoveAgency(ID);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public System.Collections.Generic.List<Tour_Agency> Agencies() {
            return base.Channel.Agencies();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public uint NextAgencyNumber() {
            return base.Channel.NextAgencyNumber();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="reservation"></param>
        /// <returns></returns>
        public bool AddReservation(Reservation reservation) {
            return base.Channel.AddReservation(reservation);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ReservationID"></param>
        /// <param name="ArrivalDate"></param>
        /// <param name="Days"></param>
        /// <returns></returns>
        public bool UpdateReservation(uint ReservationID, System.Nullable<System.DateTime> ArrivalDate, uint Days) {
            return base.Channel.UpdateReservation(ReservationID, ArrivalDate, Days);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ReservationID"></param>
        /// <param name="room"></param>
        /// <param name="ArrivalDate"></param>
        /// <param name="Days"></param>
        /// <returns></returns>
        public bool UpdateSingleReservation(uint ReservationID, Room room, System.Nullable<System.DateTime> ArrivalDate, uint Days) {
            return base.Channel.UpdateSingleReservation(ReservationID, room, ArrivalDate, Days);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ReservationID"></param>
        /// <param name="rooms"></param>
        /// <param name="ArrivalDate"></param>
        /// <param name="Days"></param>
        /// <returns></returns>
        public bool UpdateGroupReservation(uint ReservationID, System.Collections.Generic.List<Room> rooms, System.Nullable<System.DateTime> ArrivalDate, uint Days) {
            return base.Channel.UpdateGroupReservation(ReservationID, rooms, ArrivalDate, Days);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public bool RemoveReservation(uint ID) {
            return base.Channel.RemoveReservation(ID);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public System.Collections.Generic.List<Reservation> Reservations() {
            return base.Channel.Reservations();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public uint NextReservationNumber() {
            return base.Channel.NextReservationNumber();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public uint ReservationsPrice() {
            return base.Channel.ReservationsPrice();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <returns></returns>
        public uint cancelReservations(System.DateTime start, System.DateTime end) {
            return base.Channel.cancelReservations(start, end);
        }
    }
}
