//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLForms.BL_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BL_ServiceReference.IBL_SOAP")]
    public interface IBL_SOAP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/AddRoom", ReplyAction="http://tempuri.org/IBL_SOAP/AddRoomResponse")]
        bool AddRoom(BE.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/UpdateRoom", ReplyAction="http://tempuri.org/IBL_SOAP/UpdateRoomResponse")]
        bool UpdateRoom(uint ID, uint Beds, System.Nullable<BE.RoomType> Type, uint Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/RemoveRoom", ReplyAction="http://tempuri.org/IBL_SOAP/RemoveRoomResponse")]
        bool RemoveRoom(uint ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/Rooms", ReplyAction="http://tempuri.org/IBL_SOAP/RoomsResponse")]
        System.Collections.Generic.List<BE.Room> Rooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/NextRoomNumber", ReplyAction="http://tempuri.org/IBL_SOAP/NextRoomNumberResponse")]
        uint NextRoomNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/reservedRooms", ReplyAction="http://tempuri.org/IBL_SOAP/reservedRoomsResponse")]
        System.Collections.Generic.List<uint> reservedRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/availableRooms", ReplyAction="http://tempuri.org/IBL_SOAP/availableRoomsResponse")]
        System.Collections.Generic.List<BE.Room> availableRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, System.Predicate<BE.Room> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/roomIsAvailable", ReplyAction="http://tempuri.org/IBL_SOAP/roomIsAvailableResponse")]
        bool roomIsAvailable(uint ID, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/AddAgency", ReplyAction="http://tempuri.org/IBL_SOAP/AddAgencyResponse")]
        bool AddAgency(BE.Tour_Agency agency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/UpdateAgency", ReplyAction="http://tempuri.org/IBL_SOAP/UpdateAgencyResponse")]
        bool UpdateAgency(uint ID, string Name, string ContactPerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/RemoveAgency", ReplyAction="http://tempuri.org/IBL_SOAP/RemoveAgencyResponse")]
        bool RemoveAgency(uint ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/Agencies", ReplyAction="http://tempuri.org/IBL_SOAP/AgenciesResponse")]
        System.Collections.Generic.List<BE.Tour_Agency> Agencies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/NextAgencyNumber", ReplyAction="http://tempuri.org/IBL_SOAP/NextAgencyNumberResponse")]
        uint NextAgencyNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/AddReservation", ReplyAction="http://tempuri.org/IBL_SOAP/AddReservationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BE.Group_Reservation<System.Collections.Generic.List<BE.Room>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BE.Single_Reservation))]
        bool AddReservation(BE.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/UpdateReservation", ReplyAction="http://tempuri.org/IBL_SOAP/UpdateReservationResponse")]
        bool UpdateReservation(uint ReservationID, System.Nullable<System.DateTime> ArrivalDate, uint Days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/UpdateSingleReservation", ReplyAction="http://tempuri.org/IBL_SOAP/UpdateSingleReservationResponse")]
        bool UpdateSingleReservation(uint ReservationID, BE.Room room, System.Nullable<System.DateTime> ArrivalDate, uint Days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/UpdateGroupReservation", ReplyAction="http://tempuri.org/IBL_SOAP/UpdateGroupReservationResponse")]
        bool UpdateGroupReservation(uint ReservationID, System.Collections.Generic.List<BE.Room> rooms, System.Nullable<System.DateTime> ArrivalDate, uint Days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/RemoveReservation", ReplyAction="http://tempuri.org/IBL_SOAP/RemoveReservationResponse")]
        bool RemoveReservation(uint ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/Reservations", ReplyAction="http://tempuri.org/IBL_SOAP/ReservationsResponse")]
        System.Collections.Generic.List<BE.Reservation> Reservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/NextReservationNumber", ReplyAction="http://tempuri.org/IBL_SOAP/NextReservationNumberResponse")]
        uint NextReservationNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/ReservationsPrice", ReplyAction="http://tempuri.org/IBL_SOAP/ReservationsPriceResponse")]
        uint ReservationsPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBL_SOAP/cancelReservations", ReplyAction="http://tempuri.org/IBL_SOAP/cancelReservationsResponse")]
        uint cancelReservations(System.DateTime start, System.DateTime end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBL_SOAPChannel : PLForms.BL_ServiceReference.IBL_SOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BL_SOAPClient : System.ServiceModel.ClientBase<PLForms.BL_ServiceReference.IBL_SOAP>, PLForms.BL_ServiceReference.IBL_SOAP {
        
        public BL_SOAPClient() {
        }
        
        public BL_SOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BL_SOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BL_SOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BL_SOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddRoom(BE.Room room) {
            return base.Channel.AddRoom(room);
        }
        
        public bool UpdateRoom(uint ID, uint Beds, System.Nullable<BE.RoomType> Type, uint Price) {
            return base.Channel.UpdateRoom(ID, Beds, Type, Price);
        }
        
        public bool RemoveRoom(uint ID) {
            return base.Channel.RemoveRoom(ID);
        }
        
        public System.Collections.Generic.List<BE.Room> Rooms() {
            return base.Channel.Rooms();
        }
        
        public uint NextRoomNumber() {
            return base.Channel.NextRoomNumber();
        }
        
        public System.Collections.Generic.List<uint> reservedRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.reservedRooms(start, end);
        }
        
        public System.Collections.Generic.List<BE.Room> availableRooms(System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, System.Predicate<BE.Room> predicate) {
            return base.Channel.availableRooms(start, end, predicate);
        }
        
        public bool roomIsAvailable(uint ID, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.roomIsAvailable(ID, start, end);
        }
        
        public bool AddAgency(BE.Tour_Agency agency) {
            return base.Channel.AddAgency(agency);
        }
        
        public bool UpdateAgency(uint ID, string Name, string ContactPerson) {
            return base.Channel.UpdateAgency(ID, Name, ContactPerson);
        }
        
        public bool RemoveAgency(uint ID) {
            return base.Channel.RemoveAgency(ID);
        }
        
        public System.Collections.Generic.List<BE.Tour_Agency> Agencies() {
            return base.Channel.Agencies();
        }
        
        public uint NextAgencyNumber() {
            return base.Channel.NextAgencyNumber();
        }
        
        public bool AddReservation(BE.Reservation reservation) {
            return base.Channel.AddReservation(reservation);
        }
        
        public bool UpdateReservation(uint ReservationID, System.Nullable<System.DateTime> ArrivalDate, uint Days) {
            return base.Channel.UpdateReservation(ReservationID, ArrivalDate, Days);
        }
        
        public bool UpdateSingleReservation(uint ReservationID, BE.Room room, System.Nullable<System.DateTime> ArrivalDate, uint Days) {
            return base.Channel.UpdateSingleReservation(ReservationID, room, ArrivalDate, Days);
        }
        
        public bool UpdateGroupReservation(uint ReservationID, System.Collections.Generic.List<BE.Room> rooms, System.Nullable<System.DateTime> ArrivalDate, uint Days) {
            return base.Channel.UpdateGroupReservation(ReservationID, rooms, ArrivalDate, Days);
        }
        
        public bool RemoveReservation(uint ID) {
            return base.Channel.RemoveReservation(ID);
        }
        
        public System.Collections.Generic.List<BE.Reservation> Reservations() {
            return base.Channel.Reservations();
        }
        
        public uint NextReservationNumber() {
            return base.Channel.NextReservationNumber();
        }
        
        public uint ReservationsPrice() {
            return base.Channel.ReservationsPrice();
        }
        
        public uint cancelReservations(System.DateTime start, System.DateTime end) {
            return base.Channel.cancelReservations(start, end);
        }
    }
}
